### ISSUE TITLE
OSX: Crash when Cmd-Tab with open modal dialog

### ISSUE THREAD

**Issue by petr-panteleyev** [javafxports/openjdk-jfx#257] opened 2018-10-25 18:54 UTC
Java FX application crashes if it has modal dialog opened and the user switches to another application via Command-Tab. Depending on the dialog complexity it may take more that one switches to encounter the issue.

How to reproduce:

1. Build attached project with jdk-11
   $ mvn clean package
2. Run the program, 
   $ cd target/jmods
   $ java --module-path . -m dialogcrash/bug.report.DialogCrash
3  Push the button to open the dialog
3. Command-Tab to other application 2-3 times. Sometimes one is enough.
4. Observe crash message similar to attached.

macOS Mojave
version 10.14

$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

[crash.txt](https://github.com/javafxports/openjdk-jfx/files/2516314/crash.txt)
[dialogcrash.zip](https://github.com/javafxports/openjdk-jfx/files/2516318/dialogcrash.zip)

**Comment by kevinrushforth** [comment] 2018-10-25 18:58
This is already tracked in JBS as [JDK-8211304](https://bugs.openjdk.java.net/browse/JDK-8211304).

**Comment by kevinrushforth** [comment] 2018-11-06 23:15
Closing as a duplicate of [JDK-8211304](https://bugs.openjdk.java.net/browse/JDK-8211304). I'll submit a preliminary pull request shortly.

**Closed by kevinrushforth** 2018-11-06 23:15 UTC
Labels: bug, duplicate
