### ISSUE TITLE
Undecorated JavaFX windows should support Windows minimize & maximize animations

### ISSUE THREAD

**Issue by TX256** [javafxports/openjdk-jfx#263] opened 2018-11-03 13:42 UTC
(I hope it is okay to duplicate this issue here: this was posted already on the JavaFX mailing list, but this place seems to be more lively)

As the title says. Currently, undecorated Stages on Windows just instantly
disappear/appear when iconified/maximized. This looks quite unprofessional.

There are many examples out there of undecorated applications that behave like decorated applications. For example, Visual Studio Code just recently added support for undecorated frames, and they behave beautifully. Steam - the gaming platform client - is another example that has had this for a long time.

In addition (and related) to this, undecorated Stages cannot be minimized/restored by
clicking the taskbar-icon, without some JNA hackery.

For some more details, see this StackOverflow post:
https://stackoverflow.com/questions/51008461/javafx-minimizing-maximing-undecorated-stage-with-animations

**Comment by kevinrushforth** [comment] 2018-11-03 15:35
This is a duplicate of the already-filed JBS issue, [JDK-8211907](https://bugs.openjdk.java.net/browse/JDK-8211907). Note that the issue tracker in this Github mirror is only for convenience. JBS is the official bug database for the OpenJFX project.

Closing as a duplicate.

**Closed by kevinrushforth** 2018-11-03 15:35 UTC
Labels: duplicate, enhancement
