### ISSUE TITLE
Drag'n'drop doesn't work properly on KDE 5

### ISSUE THREAD

**Issue by graynk** [javafxports/openjdk-jfx#381] opened 2019-02-18 05:41 UTC
I can start dragging, but I can't finish it without fiddling around. The cursor just doesn't change after releasing mouse button (and item doesn't drop), it still suggests that I need to drop an item, even though I viciously click around all over the place. It keeps changing between drop suggestion and "can't drop here". Usually through some combination of LMB/RMB clicks and Escape presses I manage to drop an item, but it obviously shouldn't work that way. 
I observed this behavior both in my application and in SceneBuilder. Just try to drag'n'drop something in hierarchy tree node and you will see what I mean.

OS: KDE Neon 5.15 x64
OpenJFX 11.0.2

[2019-02-18 10-50-19.zip](https://github.com/javafxports/openjdk-jfx/files/2874207/2019-02-18.10-50-19.zip)
Here's a video example.

**Comment by fthevenet** [comment] 2019-03-03 10:53
I have encountered similar issues with drag and drop on Ubuntu 18.04, running Gnome 3.
Though I don't know the root cause, I suspect it is related to other compatibility issues in between OpenJFX, gtk-3 and XWayland.

In any case, know that I've had good results working around my drag and drop problem forcing OpenJFX to fall back to gtk-2, by setting the jdk.gtk.version property:
```
-Djdk.gtk.version=2
```

**Comment by dbadura** [comment] 2019-04-13 17:43
The same on situation on Ubuntu 18.04 with Gnome 3. 
Enable gtk2 with simple example works, but with more fancy it doesn't.
I found related (bug)[https://bugs.openjdk.java.net/browse/JDK-8211302]

**Comment by kevinrushforth** [comment] 2019-04-17 15:21
This duplicates [JDK-8211302](https://bugs.openjdk.java.net/browse/JDK-8211302). The workaround, is as you noted, to force GTK 2. A fix is in process.

Closing this issue as a duplicate.

**Closed by kevinrushforth** 2019-04-17 15:21 UTC
Labels: duplicate
