### ISSUE TITLE
Can't run java programm.

### ISSUE THREAD

**Issue by Maybelater2019** [javafxports/openjdk-jfx#423] opened 2019-03-28 16:20 UTC
I have since 3 days a problem with javafx 12 and i don't find the correct solution for this problem:

```
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:243)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:835)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: No toolkit found
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	... 5 more

```

**Comment by guiguidu60** [comment] 2019-03-31 12:45
I remember having the same problem but I can not remember the solution... ^^'
Did you run this on Linux or Windows ?

**Comment by avdain** [comment] 2019-03-31 14:06
I have performed the action with the Windows 10 (OS) operating system.

**Comment by guiguidu60** [comment] 2019-03-31 16:57
Did you try with JavaFX 11 ?
Did you run the program inside the IDE ?
Do you use Eclipse or Intellij ?

**Comment by Maybelater2019** [comment] 2019-03-31 17:38
When I run it with JavaFX 11, the same error is thrown out.

I am using Intellij IDEA

**Comment by Maybelater2019** [comment] 2019-03-31 20:17
When I run it in Java 8 everything works perfectly. But when i run it in JavaFX 11 a error is thrown out.

**Comment by Maybelater2019** [comment] 2019-03-31 20:27
When I run it in Java 8 everything works perfectly. But when i run it in JavaFX 11 a error is thrown out.

**Comment by guiguidu60** [comment] 2019-04-01 08:27
Create a new project.
Create a single class in a package:
```
public class MainFX extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {

        primaryStage.setTitle("Test");
        primaryStage.setOnCloseRequest(e -> Platform.exit());
        primaryStage.setScene(new Scene(new BorderPane(), 1280, 720));
        primaryStage.show();
    }
}
```
Create a module descriptor:
```
module your_module_name {

    requires javafx.graphics;

    exports your.package;
}
```
Add javafx librairies to module dependencies: File -> ProjectStructure -> Modules (in left panel) -> Dependencies (tab) -> plus button (at right) -> Jars or Directories -> Find "javafx.base" and "javafx.graphics" in javafx-sdk-12/lib directory.

Run the program. Normally, it does works fine.

**Comment by Maybelater2019** [comment] 2019-04-01 16:51
Still doesn't work.

**Comment by guiguidu60** [comment] 2019-04-02 04:09
Create a new project and try this code:
```
import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class MainFX extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {

        primaryStage.setOnCloseRequest(e -> Platform.exit());
        primaryStage.setScene(new Scene(new BorderPane(), 1280, 720));
        primaryStage.show();
    }
}
```
```
module your_module_name {

    requires javafx.graphics;

    exports your.package;
}
```

**Comment by Maybelater2019** [comment] 2019-04-02 15:30
Does not work. :(

**Comment by Maybelater2019** [comment] 2019-04-02 15:49
When I used JavaFX 11 earlier everything went perfect, everything worked. When I downloaded JavaFX 12 and tracked exactly the steps as in JavaFX 11, nothing worked anymore. When I downloaded JavaFX 12 I deleted JavaFX 11 because I thought I would not use JavaFX 11 anymore. When I wanted to run a program in JavaFX 12, nothing worked. Only one list of errors came out, it worked perfectly in the old version of JavaFX 11. I wanted to download the JavaFX 11 version again, because I wanted to see if this list of errors again come out. And yes, a list of mistakes came out. I then noticed something that was not there in the past. And although was in the public version where you can download JavaFX no longer "**11**" but "**11.0.2**" maybe it?

**Comment by Maybelater2019** [comment] 2019-04-02 16:30
I will continue programming with Java 8 JDK until the problem is solved ...

**Comment by guiguidu60** [comment] 2019-04-02 19:04
You should try to create a fresh installation of Intellij, OpenJDK and JavaFX (don't forgot to save intellij config and delete its config folder after that).
The error you have is common on Internet: you may have more help on stackoverflow website.

Please close the issue, thanks ;)

**Comment by nlisker** [comment] 2019-04-04 22:36
Seems like a configuration issue in your setup. Nothing changed in this regard between 11 and 12. I suggest that you create a new project following the instructions in https://openjfx.io/openjfx-docs/.

**Comment by Maybelater2019** [comment] 2019-04-05 14:24
Hello, I followed the steps, it does not solve the problem.

**Comment by kevinrushforth** [comment] 2019-04-05 16:29
I suspect that there is either something unique about your setup, or that you didn't follow exactly the instruction for setting up IntelliJ to run with JavaFX 12.

One additional suggestion: Run your test program with `java -Djavafx.verbose=true` which will list where it is trying to load the DLLs from. Maybe this will help shed light on your problem.

Since no one else has been able to reproduce your problem, I am closing this bug.

**Closed by kevinrushforth** 2019-04-05 16:29 UTC

**Comment by gergang** [comment] 2020-04-19 15:49
> Ok, finally, I found your problem: You separated javafx librairies from the sdk directory.
> When you extract the javafx-sdk archive, you must not move librairies (from javafx-sdk-12/lib directory) because JavaFX need included binaries for execution.
> So, inside Intellij, add javafx librairies from the javafx-sdk directory (javafx-sdk-12/lib) to your project and it works.

Thanks guiguidu60. That was precisely my problem. I had extracted the /lib directory from openjfx sdk zip file but not the /bin directory. So that's what the dll files are for in /bin.
