### ISSUE TITLE
JDK-8219917: [WebView] Sub-resource integrity check fails on Windows and Linux

### ISSUE THREAD

**Issue by erichiller** [javafxports/openjdk-jfx#230] opened 2018-10-01 15:23 UTC
I am unable to load a site using `WebView`. The specific site I'm trying on is Microsoft's oauth site. The error from the web console is:
```
Console: [null:0] Cannot load stylesheet https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/converged.v2.login.min_t7iocdq0wq2qh0nv233jig2.css. Failed integrity metadata check.
Console: [https://login.microsoftonline.com/common/oauth2/v2.0/authorize?.... Cannot load stylesheet https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/converged.v2.login.min_t7iocdq0wq2qh0nv233jig2.css. Failed integrity metadata check.
Console: [https://login.microsoftonline.com/common/oauth2/v2.0/authorize?.... Cannot load stylesheet https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/converged.v2.login.min_t7iocdq0wq2qh0nv233jig2.css. Failed integrity metadata check.
Console: [https://login.microsoftonline.com/common/oauth2/v2.0/authorize?.... Failed to load external resource ['https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/converged.v2.login.min_t7iocdq0wq2qh0nv233jig2.css']
Console: [null:0] Cannot load script https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/oldconvergedlogin_pcore.min_ueaoy8qjjryroqi9aubaoa2.js. Failed integrity metadata check.
Console: [null:0] Cannot load script https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/convergedloginpaginatedstrings-en.min_9eyqxjb02ixrn2nkbabbcq2.js. Failed integrity metadata check.
Console: [null:0] Cannot load script https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/oldconvergedlogin_pcore.min_ueaoy8qjjryroqi9aubaoa2.js. Failed integrity metadata check.
Console: [null:0] Cannot load script https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/convergedloginpaginatedstrings-en.min_9eyqxjb02ixrn2nkbabbcq2.js. Failed integrity metadata check.
Console: [null:0] Cannot load script https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/oldconvergedlogin_pcore.min_ueaoy8qjjryroqi9aubaoa2.js. Failed integrity metadata check.
Console: [https://login.microsoftonline.com/common/oauth2/v2.0/authorize?.... Failed to load external resource ['https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/oldconvergedlogin_pcore.min_ueaoy8qjjryroqi9aubaoa2.js']
Console: [null:0] Cannot load script https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/convergedloginpaginatedstrings-en.min_9eyqxjb02ixrn2nkbabbcq2.js. Failed integrity metadata check.
Console: [https://login.microsoftonline.com/common/oauth2/v2.0/authorize?.... Failed to load external resource ['https://secure.aadcdn.microsoftonline-p.com/ests/2.1.8148.16/content/cdnbundles/convergedloginpaginatedstrings-en.min_9eyqxjb02ixrn2nkbabbcq2.js']
```
(params replaced with `...`)
This happened with JavaFX 8 and after reworking with OpenJFX 11, the same error occurred.

I tried adding `sun.net.http.allowRestrictedHeaders=true` as several online similar issues suggested, but that did not affect the errors.

The System Properties (in-runtime printout):
```
{sun.desktop=windows, awt.toolkit=sun.awt.windows.WToolkit, java.specification.version=10, file.encoding.pkg=sun.io, sun.cpu.isalist=amd64, sun.jnu.encoding=Cp1252, java.class.path=C:\dev\src\github.com\erichiller\marshal-kotlin\build\classes\kotlin\main;C:\dev\lib\java\tornadofx-1.7.18-SNAPSHOT.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.2.70\17bdfaa19afad44a641a778a1cacc53b0e95dddc\kotlin-stdlib-jdk8-1.2.70.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-analyzers-common\7.4.0\e1afb580df500626a1c695e0fc9a7e8a8f58bcac\lucene-analyzers-common-7.4.0.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-codecs\7.4.0\a9da1b39322df815da029d656baad7fa4e037dce\lucene-codecs-7.4.0.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-queryparser\7.4.0\8e58add0d0c39df97d07c8e343041989bf4b3a3f\lucene-queryparser-7.4.0.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-core\7.4.0\730d9ac80436c8cbc0b2a8a749259be536b97316\lucene-core-7.4.0.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\com.github.kittinunf.fuel\fuel\1.15.0\aefaf63dbea0b9d83b161728a4540f6463e3bd22\fuel-1.15.0.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.openjfx\javafx-web\11\5c8a3b6cacde832437dff8e21a82749b5f66c1cf\javafx-web-11-win.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.openjfx\javafx-controls\11\af8d24de44e16a19ae959028eb23a48c145fb682\javafx-controls-11-win.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.openjfx\javafx-controls\11\58d961774262ec972bf304e16c154a8e18c2050b\javafx-controls-11.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.openjfx\javafx-media\11\b7a33f3ff0cad17af71e883c0921bc6819cad9c8\javafx-media-11-win.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.openjfx\javafx-media\11\586c51942ea38145727e345387b6b7cd53de0b33\javafx-media-11.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.openjfx\javafx-graphics\11\9345c7ea43dbcc73a62eca5332717b4ce617e6c6\javafx-graphics-11-win.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.openjfx\javafx-graphics\11\a736dd079047ec0b72b8c4970842a5c5e0c19f2f\javafx-graphics-11.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.openjfx\javafx-base\11\ad3a4acfaa28b484d30c40c1f009445cc3f6e68b\javafx-base-11-win.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.openjfx\javafx-base\11\9fcd3e8e3227ec97bf503f7991fad1f3b14d005\javafx-base-11.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.2.70\9318bb9dadaa56534ac8b0728a1ffa2bd0e48b28\kotlin-stdlib-jdk7-1.2.70.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\com.github.kittinunf.result\result\1.5.0\1be1ca0a17fe24ac18716e8193c7f38e847c4212\result-1.5.0.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.2.70\b5b9449f73ce7bf312e89a7560cb3c209a0fa13e\kotlin-stdlib-1.2.70.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-queries\7.4.0\229a50e6d9d4db076f671c230d493000c6e2972c\lucene-queries-7.4.0.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-sandbox\7.4.0\1692604fa06a945d1ee19939022ef1a912235db3\lucene-sandbox-7.4.0.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.2.70\6ea722d7d0b9451293e739076ddb6a4108d57b6b\kotlin-stdlib-common-1.2.70.jar;C:\dev\conf\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar, java.vm.vendor="Oracle Corporation", sun.arch.data.model=64, user.variant=, java.vendor.url=http://java.oracle.com/, user.timezone=, os.name=Windows 10, java.vm.specification.version=10, sun.java.launcher=SUN_STANDARD, user.country=US, sun.boot.library.path=C:\dev\lib\jdk\jdk-10.0.2\bin, sun.java.command=ai.marshal.desktop.AppKt, jdk.debug=release, sun.cpu.endian=little, user.home=C:\Users\eric, user.language=en, java.specification.vendor=Oracle Corporation, java.version.date=2018-07-17, java.home=C:\dev\lib\jdk\jdk-10.0.2, file.separator=\, java.vm.compressedOopsMode=Zero based, line.separator=
, java.specification.name=Java Platform API Specification, java.vm.specification.vendor=Oracle Corporation, java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment, user.script=, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, java.runtime.version=10.0.2+13, user.name=eric, path.separator=;, os.version=10.0, java.runtime.name=OpenJDK Runtime Environment, file.encoding=UTF-8, sun.net.http.allowRestrictedHeaders=true, java.vm.name=OpenJDK 64-Bit Server VM, java.vendor.version=18.3, java.vendor.url.bug=http://bugreport.java.com/bugreport/, java.io.tmpdir=C:\Users\eric\AppData\Local\Temp\, java.version=10.0.2, user.dir=C:\dev\src\github.com\erichiller\marshal-kotlin, os.arch=amd64, java.vm.specification.name=Java Virtual Machine Specification, java.awt.printerjob=sun.awt.windows.WPrinterJob, sun.os.patch.level=, java.library.path=C:\dev\lib\jdk\jdk-10.0.2\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\WindowsPowerShell\Modules\omega\system\git\cmd;C:\Program Files\WindowsPowerShell\Modules\omega\system\python\;C:\Program Files\WindowsPowerShell\Modules\omega\system\python\Scripts;C:\Program Files\WindowsPowerShell\Modules\omega\bin;C:\Program Files\WindowsPowerShell\Modules\omega\system\nodejs;C:\Program Files\WindowsPowerShell\Modules\omega\system\vim;C:\dev\lib\javafx-sdk-11\bin;C:\Users\eric\AppData\Local\Microsoft\WindowsApps;;C:\Users\eric\AppData\Local\Programs\Microsoft VS Code\bin;., java.vendor=Oracle Corporation, java.vm.info=mixed mode, java.vm.version=10.0.2+13, sun.io.unicode.encoding=UnicodeLittle, java.class.version=54.0}
```

JavaVM is 10.0.2

I am relatively sure that the issue is with CORS (I am loading `microsoftonline.com` and the resources are on `microsoftonline-p.com`). I've tried every possible fix that I can think of, or find online.

I have tried setting all of these

    engine.setJavaScriptEnabled(true)

    engine.setUserAgent("AppleWebKit/537.44")

    System.setProperty("sun.net.http.allowRestrictedHeaders", "true")

I've also set the Property via `-Dsun.net.http.allowRestrictedHeaders=true` in `VMOptions` ( as seen [here](https://stackoverflow.com/questions/44905264/cannot-sign-in-to-google-in-javafx-webview) ) and from the JavaFX issue [JDK-8096797](https://bugs.openjdk.java.net/browse/JDK-8096797)

The property shows up as set:

    println(System.getProperty("sun.net.http.allowRestrictedHeaders"))

yields `true` on the console printout.

Still no change, ever in the page output, it is always a white, blank screen, and the same errors from the web console.

I think I found the [trouble lines in WebKit(see `matchIntegrityMetadata`)](https://github.com/WebKit/webkit/blob/89c28d471fae35f1788a0f857067896a10af8974/Source/WebCore/loader/SubresourceIntegrity.cpp) even, but that didn't help me solve the problem any, because I don't know how to disable the _integrityCheck_.

For reference, here is the entire method:

    private fun WebView.authWindow(provider: Oath2Account){
    	engine.setUserAgent("AppleWebKit/537.44")
    	engine.setJavaScriptEnabled(true)
    	URLPermission("https://*.com")
    	System.setProperty("sun.net.http.allowRestrictedHeaders", "true")
    
    	Platform.runLater {
    		engine.userDataDirectory = File("C:\\users\\eric\\javafx_tmp")
    		engine.setOnError { println("IN PAGE ERROR --> $it") }
    		engine.setOnAlert { println("IN PAGE ALERT --> $it") }
    		engine.setConfirmHandler { println("IN PAGE CONFIRM HANDLER --> $it")
    		true
    		}
    		engine.setCreatePopupHandler { println("IN PAGE POPUP --> $it")
    		engine}
    		engine.setOnResized {   println("IN PAGE RESIZED --> $it") }
    		engine.setOnStatusChanged {   println("IN PAGE STATUS CHANGED --> $it")
    			println("\t${it.data}")
    			println("\t${it.source}")
    			println("\t${it.eventType}")
    			println("\t${it.target}")
    			println("\t${it.isConsumed}")
    
    		}
    		engine.setOnVisibilityChanged { println("IN PAGE VISIBILITY CHANGED --> $it") }
    		engine.setPromptHandler { println("IN PAGE PROMPTED --> $it")
    		"HELLO"}
    		println("JavaScript engine status: ${engine.isJavaScriptEnabled}")
    
    		println("engine is loading $loadURL")
    		engine.locationProperty().addListener { observable, oldLocation, newLocation->
    			println("observable=$observable\noldLocation=$oldLocation\nnewLocation=$newLocation")
    			//			if (newLocation.startsWith("urn:ietf:wg:oauth:2.0:oob")) {
    			//				val code:get
    			//				val title:from
    			//				val accessToken = service.getAccessToken(verifier)
    			//				doSomething(accessToken.getAccessToken())
    			//			}
    		}
    		com.sun.javafx.webkit.WebConsoleListener.setDefaultListener { webview, message, lineNumber, sourceId -> println("Console: [$sourceId:$lineNumber] $message") }
    		engine.setOnError({ event -> System.out.println(event.getMessage()) })
    		try{
    		engine.load(loadURL )
    	} catch (e: IOException) {
    		println("caught error:")
    		e.printStackTrace();
    	}
    }

**Comment by kevinrushforth** [comment] 2018-10-01 15:27
@ararunprasad @muralibilla can you comment on this?

**Comment by golebiow** [comment] 2018-10-17 18:20
Anything new in this topic?

**Comment by cuc2017** [comment] 2018-11-15 22:56
I am having the same issue using Java 8 (version 191). My code is the same as the above and it works on Mac but not on Windows (both 7 and 10). If I use an earlier version of Java 8 (121) it works.

**Comment by infosuitemka** [comment] 2018-11-16 03:00
I am out of the office until 19-11-2018.

I will respond to your message when I return.


Note: This is an automated response to your message  "Re: [javafxports/openjdk-jfx] `Failed integrity metadata check.` in JavaFX WebView, ignores SystemProp (#230)" sent on 15.11.2018 23.56.41. 

This is the only notification you will receive while this person is away.

**Comment by ararunprasad** [comment] 2018-11-16 08:32
Sorry for missing this thread. I will take a look.

**Comment by ararunprasad** [comment] 2018-11-16 08:43
I couldn't load the site(microsoftonline.com) mentioned in the bug description in any browser. @erichiller, which site you are trying to load exactly?

**Comment by infosuitemka** [comment] 2018-11-16 09:00
I am out of the office until 19-11-2018.

I will respond to your message when I return.


Note: This is an automated response to your message  "Re: [javafxports/openjdk-jfx] `Failed integrity metadata check.` in JavaFX WebView, ignores SystemProp (#230)" sent on 16.11.2018 9.43.28. 

This is the only notification you will receive while this person is away.

**Comment by infosuitemka** [comment] 2018-11-16 09:00
I am out of the office until 19-11-2018.

I will respond to your message when I return.


Note: This is an automated response to your message  "Re: [javafxports/openjdk-jfx] `Failed integrity metadata check.` in JavaFX WebView, ignores SystemProp (#230)" sent on 16.11.2018 9.32.33. 

This is the only notification you will receive while this person is away.

**Comment by muralibilla** [comment] 2018-11-16 09:19
i think the site which @erichiller  trying to load is https://login.microsoftonline.com/. When we try to load in hellowebview, i see the redirected url is "https://login.microsoftonline.com/common/oauth2/authorize?client_id=......."  and displays blank page where as in other browsers, i see a Microsoft Sign in page.

When i tried in HelloWebView, i see 502 Bad Gateway in wireshark.

HTTP/1.1 502 Bad Gateway
Via: 1.1 10.177.38.113 (McAfee Web Gateway 7.7.2.17.0.26803)
Date: Fri, 16 Nov 2018 09:16:11 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 332
Referrer-Policy: no-referrer
Proxy-Connection: Keep-Alive

**Comment by mguessan** [comment] 2018-12-04 16:53
Had the same issue on DavMail, see:
https://github.com/mguessan/davmail/issues/12

I noticed the webkit ticket explicitly mentioned sha256, maybe the Microsoft sha384 hash is not supported ?

`integrity="sha384-K7b+bnr8ZFNdmq6AKvC2r18dCqNdwNHT//9U+Y1pOYU5BZo7t+s1+tuvmYEz2Nay"`

Ticket: https://bugs.webkit.org/show_bug.cgi?id=148363

**Comment by Maxoudela** [comment] 2019-02-25 09:23
I do confirm I have the exact same issue when displaying an authentification page from Okta ( https://www.okta.com) in the WebView.

**Comment by ararunprasad** [comment] 2019-02-25 14:40
> I do confirm I have the exact same issue when displaying an authentification page from Okta ( https://www.okta.com) in the WebView.
Which option should I try? "Try now" or "sign in"? Should I create an account to reproduce the issue?

**Comment by Maxoudela** [comment] 2019-02-25 15:32
You should try the free trial : https://www.okta.com/free-trial/
It should allow you to create a SSO connection using okta. Then, you will be able to log into okta using SAML. When doing so, a form should be showing up allowing you to enter your credentials. It is happening in a browser, but not in the webview and I suspect this issue to be the reason.

**Comment by mguessan** [comment] 2019-02-25 18:33
I can confirm this is a resource integrity check issue, see my workaround at:
https://github.com/mguessan/davmail/commit/6553fe02edcc9d5c64c7725ec8a653d5f661cd2e

You don't need to create your own Okta instance to reproduce this, just access:
https://login.microsoftonline.com
and enter an email address of an Okta protected domain.
=> will send you one by private message

**Comment by Maxoudela** [comment] 2019-02-26 10:45
Hi @mguessan , thanks for the hint.

I've been able to test your solution and the credentials are indeed appearing. However I now have this error : https://devforum.okta.com/t/password-grant-bad-request-accept-and-or-content-type-headers-likely-do-not-match-supported-values/2346

Seems like I'm sending Json somehow and Okta doesn't like it. But that looks like an issue on my side rather than on the JavaFX webView.

We should find a solution on OpenJFX quick as the work-around is really not beautiful at all

**Comment by mguessan** [comment] 2019-02-26 18:29
I would even say that the workaround is very ugly...
Anyway if you applied it in your test case, please make sure you override httpsURLConnection *only* for form urls, this may be the cause of your "do not match supported values" error.

With current DavMail trunk code I manage to get to actual form submission. Waiting for user feedback to know if it actually works.

Anyway, back to OpenJFX: the real issue is that any external resource with an integrity signature fails to load
=> As soon as we get a fix for this I can drop my ugly workaround.

**Comment by wvdemeer** [comment] 2019-02-27 06:37
Here's a very simple demo of the problem: https://wvdemeer.github.io/index.html

In this example, the bug causes bootstrap not to load, which is very clear to see. Just open the site in a `WebView` and then compare it with the same site opened in a browser...

I'm using `WebConsoleListener.setDefaultListener` to debug the WebView, and it shows these messages:

```
Cannot load stylesheet https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css. Failed integrity metadata check.[at 0]
Cannot load script https://code.jquery.com/jquery-3.2.1.slim.min.js. Failed integrity metadata check.[at 0]
Cannot load script https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js. Failed integrity metadata check.[at 0]
Cannot load script https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js. Failed integrity metadata check.[at 0]
```


You can also test the correctness of "subresource integrity" at w3c-test, open this site in a `WebView`: http://w3c-test.org/subresource-integrity/subresource-integrity.sub.html
(I get "21 Pass" and "21 Fail" in a `WebView`)

**Comment by ararunprasad** [comment] 2019-02-27 11:30
@wvdemeer I just tested with latest build and I see that both the links you shared are working. Could you recheck using latest builds?

**Comment by wvdemeer** [comment] 2019-02-27 12:30
@ararunprasad I've tried with `12-ea+14` and `11.0.2`, both do not work for me.

**Comment by mguessan** [comment] 2019-02-27 13:36
@ararunprasad same here, not working with openjfx-12-ea+14_windows-x64

**Comment by ararunprasad** [comment] 2019-02-27 13:46
This is what I see with openjfx-12-ea+14_osx-x64_bin-sdk.zip, the same output with openjfx-11.0.2_osx-x64_bin-sdk.zip

![image](https://user-images.githubusercontent.com/3874763/53494224-3e506280-3ac3-11e9-95ff-45fbc3b1e463.png)

![image](https://user-images.githubusercontent.com/3874763/53494268-588a4080-3ac3-11e9-83fe-c5aa56a583c8.png)

I'm yet to check on Windows, but result should be identical.

**Comment by ararunprasad** [comment] 2019-02-28 11:07
It works in macOS because we use CommonCrypto based digest implementation from mac SDK and the same is unimplemented for Linux and Windows.

**Comment by ararunprasad** [comment] 2019-02-28 11:30
JBS link: https://bugs.openjdk.java.net/browse/JDK-8219917

**Closed** 2019-03-20 09:14 UTC
Labels: bug
