### ISSUE TITLE
AppVeyor CI: updating cache fails

### ISSUE THREAD

**Issue by bourgesl** [javafxports/openjdk-jfx#95] opened 2018-06-08 10:16 UTC
Appveyor CI has a (minor?) build problem:

Updating build cache...
Cache 'C:\Users\appveyor\.gradle\caches' - Updated
**Cache 'C:\Users\appveyor\.gradle\wrapper' - Calculating dependencies checksum...Error calculating dependencies CRC for C:\Users\appveyor\.gradle\wrapper: Error calculating CRC32 for C:\projects\openjdk-jfx\.gradle-wrapper\gradle-wrapper.properties: The system cannot find the path specified**
Cache 'C:\jdk10' - Up to date
Cache 'C:\ProgramData\chocolatey\bin' - Up to date
Cache 'C:\ProgramData\chocolatey\lib' - Up to date
Cache entry not found: C:\ProgramData\chocolatey\cache
Cache entry not found: C:\MSSymbols
$dbgDir = ".\javafx-debug-symbols\"
$dbgArchive = "javafx-debug-symbols.zip"

One more thing: systemTests are not run !
It is deliberately or not ?

**Comment by brcolow** [comment] 2018-06-08 21:05
The problem is simply that we don't have `.gradle-wrapper\gradle-wrapper.properties` in our project (I don't think we have a properties file specifically for `gradle-wrapper` so the entire line:

`- C:\Users\appveyor\.gradle\wrapper -> .gradle-wrapper\gradle-wrapper.properties`

Should be removed from `appveyor.yml`.

**Comment by kevinrushforth** [comment] 2018-06-08 21:20
There is a gradle/wrapper/gradle-wrapper.properties so maybe it should be changed to that?

**Comment by brcolow** [comment] 2018-06-08 22:06
Yes, that is correct. At least, it matches my intention of adding the line in the first place.

**Comment by johanvos** [comment] 2018-07-14 08:03
I wonder how it comes it doesn't fail as long as you're doing PR's in a for, but once the result is merged, it fails. That is at least why I noticed in #130. If it is not the same issue, I'll unlink.

Do we plan to add Kevin's suggestion to the appveyor file?

**Comment by brcolow** [comment] 2018-08-01 01:13
`- C:\Users\appveyor\.gradle\wrapper -> .gradle-wrapper\gradle-wrapper.properties`

Should be:

`- C:\Users\appveyor\.gradle\wrapper -> gradle\wrapper\gradle-wrapper.properties`

Get's a 👍 from me and should fix the build. Not sure why it only happens after merging, maybe some kind of Appveyor security thing.

**Comment by johanvos** [comment] 2018-08-01 01:30
Interesting. Do you want to create a PR for this?

**Comment by brcolow** [comment] 2018-08-01 22:00
Opened: https://github.com/javafxports/openjdk-jfx/pull/146

**Closed** 2018-08-01 22:46 UTC
Labels: bug
