### ISSUE TITLE
Touch events not handled properly in Glass GTK backend

### ISSUE THREAD

**Issue by jln-ho** [javafxports/openjdk-jfx#329] opened 2018-12-19 15:16 UTC
I'm working on a JavaFX project and would like to switch from Oracle JDK 1.8 to OpenJDK 11. So far the transition has been pretty seamless, but there is still one main problem related to touch/mouse input that's causing some trouble. 

The JavaFX UI is supposed to run on a touch-enabled device, which used to work straight out of the box with Oracle JDK 1.8. When I touch the screen, the following sequence of mouse events is fired as expected:

`MOUSE_PRESSED`

`MOUSE_RELEASED`

`MOUSE_CLICKED`

After building the same application with OpenJDK11 (using OpenJFX 11 as an external library as JavaFX is no longer part of the JDK by default) I get the follwing sequence of events:

`MOUSE_ENTERED_TARGET`

`MOUSE_ENTERED_TARGET`

`MOUSE_EXITED_TARGET`

`MOUSE_EXITED_TARGET`

This explains why I can't click any buttons (or controls in general). So far so good. The question is, how do I get my `MOUSE_{PRESSED,RELEASED,CLICKED}` events back?

SSCE:

````java
package com.example.jfxtouchtest;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.input.MouseEvent;
import javafx.scene.input.TouchEvent;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;


public class JFXTouchTest extends Application{

    public static void main(String[] args) {
        Application.launch(args);
    }

        @Override
        public void start(Stage primaryStage) {
            primaryStage.addEventFilter(TouchEvent.ANY, e -> System.out.println("touch event: " + e.getEventType()));
            primaryStage.addEventFilter(MouseEvent.ANY, e -> System.out.println("mouse event: " + e.getEventType()));
            primaryStage.setScene(new Scene(new Pane()));
            primaryStage.setWidth(800);
            primaryStage.setHeight(800);
            primaryStage.show();
        }
}
````
I think it's worth noting that all fired events are `MouseEvents` (not `TouchEvents`), regardless of whether I'm using the touchscreen or not. That in itself is sort of strange in my opinion, but at least I'm getting the desired behaviour with JDK 8...

Some background information:

 - OS: Ubuntu 18.04.01 LTS
 - Kernel: 4.15.0-42-generic
 - Oracle JDK 1.8.0_191
 - OpenJDK 11.0.1
 - Touchscreen (as reported by `xinput`): Atmel maXTouch Digitizer
 - The touchscreen works just fine with other applications, click events seem to be handled as expected.
 - The somehwat related VM-arguments 

    `-Dcom.sun.javafx.isEmbedded=true` and 

    `-Dcom.sun.javafx.touch=true` 

    both seem to have no effect on the issue
 - There seems to be a slight difference in the `xev` output I'm getting depending on whether I'm using the mouse or the touchscreen:  

    Mouse (`state` is `0x0` for ButtonPress, `0x100` for ButtonRelease):

        ButtonPress event, serial 34, synthetic NO, window 0x3400001,
            root 0x193, subw 0x0, time 16982696, (93,90), root:(964,612),
            state 0x0, button 1, same_screen YES
    
        ButtonRelease event, serial 34, synthetic NO, window 0x3400001,
            root 0x193, subw 0x0, time 16983364, (93,90), root:(964,612),
            state 0x100, button 1, same_screen YES

   Touchscreen (`state` is `0x100` in both cases):

        ButtonPress event, serial 34, synthetic NO, window 0x3400001,
            root 0x193, subw 0x0, time 17599475, (93,145), root:(964,667),
            state 0x100, button 1, same_screen YES

        ButtonRelease event, serial 34, synthetic NO, window 0x3400001,
            root 0x193, subw 0x0, time 17599537, (93,145), root:(964,667),
            state 0x100, button 1, same_screen YES

   I'm not exactly sure what this means, though.

Any help would be greatly appreciated, even if it's just a confirmation that the issue is reproducible on another machine with another type of touchscreen! Many thanks in advance!

**Comment by jln-ho** [comment] 2018-12-19 15:19
I have managed to get my hands on a different touchscreen in the meantime, and it seems to work fine with that one. What's interesting is that - just like with regular mouse events - `xev` reports two different statuses for ButtonPress and ButtonRelease, so maybe the status field being the same for both event types on the other touchscreen has something to do with this after all?

**Comment by jgneff** [comment] 2018-12-22 04:52
Have you tried catching the events at a lower level with the _input-events_ command (found in the _input-utils_ package on Ubuntu)? That helped me solve a problem with a keypad input device whose driver fails to send the EV_SYN event terminator. It can be helpful to compare the events reported directly from the driver with what you're getting (or not getting) in your JavaFX application.

For example, below are two different touch screen input devices showing one tap:

```ShellSession
# input-events 1
/dev/input/event1
   bustype : BUS_I2C
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "zForce-ir-touch"
   bits ev : EV_SYN EV_KEY EV_ABS

waiting for events
12:07:59.474693: EV_ABS ABS_Y 341
12:07:59.474721: EV_ABS ABS_X 280
12:07:59.474732: EV_ABS ABS_PRESSURE 101
12:07:59.474744: EV_KEY BTN_TOUCH (0x14a) pressed
12:07:59.474753: EV_SYN code=0 value=0
12:07:59.493436: EV_ABS ABS_PRESSURE 0
12:07:59.493457: EV_KEY BTN_TOUCH (0x14a) released
12:07:59.493465: EV_SYN code=0 value=0

# input-events 1
/dev/input/event1
   bustype : BUS_I2C
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "zForce-ir-touch"
   bits ev : EV_SYN EV_KEY EV_ABS

waiting for events
20:52:03.447367: EV_ABS ABS_MT_TRACKING_ID 1
20:52:03.447370: EV_ABS ABS_MT_TOUCH_MAJOR 1
20:52:03.447372: EV_ABS ABS_MT_WIDTH_MAJOR 1
20:52:03.447375: EV_ABS ABS_MT_POSITION_X 476
20:52:03.447378: EV_ABS ABS_MT_POSITION_Y 445
20:52:03.447381: EV_ABS ABS_PRESSURE 1024
20:52:03.447385: EV_KEY BTN_TOUCH (0x14a) pressed
20:52:03.447388: EV_SYN code=2 value=0
20:52:03.447390: EV_SYN code=0 value=0
20:52:03.542085: EV_ABS ABS_MT_TRACKING_ID 1
20:52:03.542090: EV_ABS ABS_MT_TOUCH_MAJOR 0
20:52:03.542091: EV_ABS ABS_MT_WIDTH_MAJOR 0
20:52:03.542094: EV_ABS ABS_MT_POSITION_X 476
20:52:03.542097: EV_ABS ABS_MT_POSITION_Y 445
20:52:03.542099: EV_ABS ABS_PRESSURE 0
20:52:03.542102: EV_KEY BTN_TOUCH (0x14a) released
20:52:03.542103: EV_SYN code=2 value=0
20:52:03.542105: EV_SYN code=0 value=0
```

**Comment by jln-ho** [comment] 2019-01-07 09:21
Good idea, thanks! 

When I run `input-events` my `bits ev` aliases (?) are all `(null)`... not sure if that's relevant at all, it just caught my eye. 

Anyway, here's the output for the problematic touchscreen:

````
/dev/input/event6
   bustype : BUS_USB
   vendor  : 0x3eb
   product : 0x214e
   version : 273
   name    : "Atmel Atmel maXTouch Digitizer"
   phys    : "usb-0000:00:14.0-6.1/input1"
   uniq    : ""
   bits ev : (null) (null) (null) (null)

waiting for events
10:03:32.285438: (null) ??? 19
10:03:32.285438: (null) ??? 2105
10:03:32.285438: (null) ??? 2459
10:03:32.285438: (null) ??? (0x14a) pressed
10:03:32.285438: (null) ??? 2105
10:03:32.285438: (null) ??? 2459
10:03:32.285438: (null) ??? 0
10:03:32.285438: (null) code=0 value=0
10:03:32.300401: (null) ??? 10000
10:03:32.300401: (null) code=0 value=0
10:03:32.315397: (null) ??? 20000
10:03:32.315397: (null) code=0 value=0
10:03:32.330431: (null) ??? 30000
10:03:32.330431: (null) code=0 value=0
10:03:32.375439: (null) ??? 91400
10:03:32.375439: (null) code=0 value=0
10:03:32.376435: (null) ??? -1
10:03:32.376435: (null) ??? (0x14a) released
10:03:32.376435: (null) ??? 91500
10:03:32.376435: (null) code=0 value=0
````

And for the other one that's working fine:

````
/dev/input/event4
   bustype : BUS_USB
   vendor  : 0x4d8
   product : 0xc02
   version : 273
   name    : "Microchip Technology Inc. AR1100"
   phys    : "usb-0000:00:14.0-6.3.2/input0"
   uniq    : ""
   bits ev : (null) (null) (null) (null)

waiting for events
10:09:32.078706: (null) ??? 2854
10:09:32.078706: (null) ??? 2854
10:09:32.078706: (null) code=0 value=0
10:09:32.079624: (null) ??? 589825
10:09:32.079624: (null) ??? (0x110) pressed
10:09:32.079624: (null) code=0 value=0
10:09:32.082614: (null) ??? 2846
10:09:32.082614: (null) ??? 2846
10:09:32.082614: (null) code=0 value=0
10:09:32.085690: (null) ??? 2843
10:09:32.085690: (null) ??? 2839
10:09:32.085690: (null) code=0 value=0
10:09:32.089687: (null) ??? 2832
10:09:32.089687: (null) code=0 value=0
10:09:32.110668: (null) ??? 2845
10:09:32.110668: (null) ??? 2828
10:09:32.110668: (null) code=0 value=0
10:09:32.118709: (null) ??? 589825
10:09:32.118709: (null) ??? (0x110) released
10:09:32.118709: (null) code=0 value=0
````

Just for reference, here's what I get with a USB mouse:
````
/dev/input/event5
   bustype : BUS_USB
   vendor  : 0x461
   product : 0x4d15
   version : 273
   name    : "USB Optical Mouse"
   phys    : "usb-0000:00:14.0-6.3.3/input0"
   uniq    : ""
   bits ev : (null) (null) (null) (null)

waiting for events
10:14:57.999240: (null) ??? 589825
10:14:57.999240: (null) ??? (0x110) pressed
10:14:57.999240: (null) code=0 value=0
10:14:58.111241: (null) ??? 589825
10:14:58.111241: (null) ??? (0x110) released
10:14:58.111241: (null) code=0 value=0
````

Not sure what to make of this, to be honest... I'm getting `pressed` and `released` events in all cases. The number reported along with these events is different for the problematic touchscreen (0x14a vs. 0x110). That's similar to the obvervation I made with the `state` field in the `xev` ouput comparison (see initial post). 

Any ideas?

**Comment by jgneff** [comment] 2019-01-14 02:40
Sorry, no ideas. You can get a second opinion, though, still outside of X11, with the `libinput-debug-events` command from the `libinput-tools` package. Here's some sample output I got by pressing and releasing the HOME key and the left mouse button on my workstation:

```ShellSession
$ sudo libinput-debug-events 
...
-event4   KEYBOARD_KEY      +4.68s	KEY_HOME (102) pressed
 event4   KEYBOARD_KEY      +4.81s	KEY_HOME (102) released
-event5   POINTER_BUTTON   +11.34s	BTN_LEFT (272) pressed, seat count: 1
 event5   POINTER_BUTTON   +11.51s	BTN_LEFT (272) released, seat count: 0
...
```

**Comment by infortel** [comment] 2019-01-16 16:03
Hi,

I have the same problem with an ELO Touch screen. 
The BUTTON_PRESS is fire with OpenJFX 11 in Windows but not with Ubuntu. With JKD8 everything works fine in both Operationg Systems.
I am very interested in this fix. Let me know if you need my collaboration for testing with my screen.
Let us know if you find a solution.

Thank you.

**Comment by jln-ho** [comment] 2019-01-30 14:49
Update: The problem only occurs for touch events inside a `Window`. `PopupWindows` work perfectly fine for some reason.

Revised SSCE:

````java
package com.example.jfxtouchtest;

import javafx.application.Application;
import javafx.collections.ListChangeListener;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.input.MouseEvent;
import javafx.scene.input.TouchEvent;
import javafx.scene.layout.Pane;
import javafx.stage.PopupWindow;
import javafx.stage.Stage;
import javafx.stage.Window;


public class JFXTouchTest {

    public static void main(String[] args) {
        Application.launch(JFXApp.class, args);
    }

    public static class JFXApp extends Application implements ListChangeListener<Window> {

        @Override
        public void start(Stage primaryStage) {
            primaryStage.addEventFilter(TouchEvent.ANY, e -> System.out.println("touch event: " + e.getEventType()));
            primaryStage.addEventFilter(MouseEvent.ANY, e -> System.out.println("mouse event: " + e.getEventType()));
            final ComboBox<String> comboBox = new ComboBox<>();
            comboBox.getItems().addAll("Test1", "Test2", "Test3");
            primaryStage.setScene(new Scene(new Pane(comboBox)));
            primaryStage.setWidth(800);
            primaryStage.setHeight(800);
            primaryStage.show();
            Window.getWindows().addListener(this);
        }

        @Override
        public void onChanged(Change<? extends Window> c) {
            if (!c.next()) return;
            for (Window w : c.getAddedSubList()) {
                if (w instanceof PopupWindow) {
                    w.addEventFilter(TouchEvent.ANY,
                            e -> System.out.println("touch event (PopupWindow): " + e.getEventType()));
                    w.addEventFilter(MouseEvent.ANY,
                            e -> System.out.println("mouse event (PopupWindow): " + e.getEventType()));
                    Window.getWindows().removeListener(this);
                }
            }
        }
    }
}
````
`MOUSE_PRESSED` and `MOUSE_RELEASED` events are fired in the `PopupWindow` (used to display the selectable items of the `ComboBox`). There is definitely something fishy going on here.

I have reported the issue to Oracle, they say they will "evaluate it for openjfx13".
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8217955

**Comment by tdudziak** [comment] 2019-01-31 17:30
I reproduced the issue with the same touchscreen ("Atmel maXTouch Digitizer", USB VID=`03eb` PID=`214e`). The problem seems to be with the touch input functionality introduced in gdk-3.4.

The glass-gtk backend in multiple places requests all possible events by using `GDK_ALL_EVENTS_MASK` (see `GdkEventMask` [here](https://developer.gnome.org/gdk3/stable/gdk3-Events.html)). In newer versions of gdk this includes `GDK_TOUCH_MASK`. When this flag is set, gdk no longer delivers `GDK_BUTTON_*` events with a touch screen but instead uses `GDK_TOUCH_*`. The event processing code in [GlassApplication.cpp](https://github.com/javafxports/openjdk-jfx/blob/50282d0fbceb358c11b3077cc0447d378236366d/modules/javafx.graphics/src/main/native-glass/gtk/GlassApplication.cpp#L452) doesn't handle these events so they're ignored.

There are several possible solutions/workarounds:

1. Force JavaFX to use gtk-2 by using the java parameter `-Djdk.gtk.version=2`. The touchscreen works with that setting although this causes other problems with our application (possibly related to 3rd party libraries).
2. Modify the gtk glass backend to exactly specify which events it's capable of handling instead of using `GDK_ALL_EVENTS_MASK`. This is what I did [here](https://github.com/tdudziak/openjdk-jfx/commit/e3ee4da575bec12bba3e8fc745e874f35061b72a) and it works for me -- touch events are delivered as mouse events like in earlier versions. I can submit a pull request if desired.
3. Handle these `GDK_TOUCH_*` events and emit a corresponding JavaFX `TouchEvent` thus introducing proper touch input support in the glass-gtk backend. I might try that in the future.

**Comment by DivineThreepwood** [comment] 2019-09-25 09:01
any progress on this issue?

**Comment by lancehzy** [comment] 2019-12-02 07:16
May I ask how can you make it work for JDK 8 and Ubuntu 18.04? Because I am having the same problem that when I touched the screen it only fired MOUSE_ENTERED_TARGET and MOUSE_EXITED_TARGET events, while I am using Orcale jdk 1.8 and Ubuntu 18.04.2

**Comment by DivineThreepwood** [comment] 2019-12-02 14:44
> Force JavaFX to use gtk-2 by using the java parameter -Djdk.gtk.version=2. The touchscreen works with that setting although this causes other problems with our application (possibly related to 3rd party libraries).

It's just a workaround but at least its working fine in my setup until the main issue gets hopefully fixed in gtk.

**Comment by kevinrushforth** [comment] 2019-12-02 15:37
This GitHub issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com/).

**Comment by jcbloewen** [comment] 2019-12-02 15:43
> This GitHub issue tracker is not actively tracked or managed. Please file a bug at [bugreport.java.com](https://bugreport.java.com/).

There already is a bug ticket open, please see above [comment by jln-ho](https://github.com/javafxports/openjdk-jfx/issues/329#issuecomment-458970768):
> I have reported the issue to Oracle, they say they will "evaluate it for openjfx13".
> https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8217955

**Comment by kevinrushforth** [comment] 2019-12-02 15:54
Here is the direct pointer to the bug in JBS: https://bugs.openjdk.java.net/browse/JDK-8217955

**Closed by kevinrushforth** 2019-12-02 15:54 UTC
Labels: duplicate
